EVG-17909: Add tests for the Logkeeper route handlers
evergreen-ci/logkeeper pull request #120
Opened 2022-10-13 03:43 UTC by julianedwards

- Add unit tests for the route handlers
- Some clean up.

2022-10-13 16:03 UTC, johndaniels requested changes

2022-10-13 16:03 UTC, johndaniels commented on views.go
> +func addCORSHeaders(w http.ResponseWriter, r *http.Request) {
Good styleguide fix.

2022-10-13 16:03 UTC, johndaniels commented on views.go
> +		return
Good catch.

2022-10-13 16:04 UTC, johndaniels commented
Just the one comment. Let me know your thoughts.

2022-10-17 15:25 UTC, julianedwards commented on views.go
> +type NewLogkeeperOptions struct {
That works for me!

2022-10-17 21:53 UTC, johndaniels approved these changes

2022-10-17 22:55 UTC, merged